<?php
/**
 * @var Model_User $user
 */
$user = $view->getParam('user');
?>

<?php if($user) : ?>
    <div id="passwordFormDiv">
        <form name="passwordForm" id="passwordForm" method="POST" autocomplete="off">
            <input type="text" name="userId" class ='hide' value="<?php echo $user->id; ?>"/>
            <label for='password1' id = 'labelPassword'>Введите ваш пароль:</label>
            <input placeholder="" type="password" name="password1" maxlength="30"/><br />
            <label for='newPassword' id = 'labelNewPassword'>Введите новый пароль:</label>
            <input placeholder="" type="password" name="newPassword"  maxlength="30"/><br />
            <input type="submit" name="update" value="Enter" />
        </form>
    </div>
<?php  elseif($view->getParam('error')) : ?>
    <div class="error"><?php echo $view->getParam('error')?></div>
<?php endif; ?>
