<div id="createFormDiv">
    <form name="createForm" id="createForm" method="POST" autocomplete="off">
        <label for='createEmail'>Email:</label>
        <input type="text" name="createEmail" maxlength="20"/><br />
        <label for='first_name'>First Name:</label>
        <input type="text" name="first_name" maxlength="30"/><br />
        <label for='last_name'>Last Name:</label>
        <input type="text" name="last_name" maxlength="30"/><br />
        <label for='year'>Year:</label>
        <input type="text" name="year" maxlength="30"/><br />
<!--        <label for='skills'>Skills:</label>
        <select id="select" name="hero[]" style="width: 150px">
            <option selected disabled>Chouse skills</option>
            <option value="HTML">HTML</option>
            <option value="CSS">CSS</option>
            <option value="PHP">PHP</option>
            <option value="Java Script">Java Script</option>
            <option value="Java">Java</option>
        </select><br />-->
        <label for='skills'>Skills:</label>
        <input type="text" name="skills" maxlength="30"/><br />
        <label for='role_id'>Role id:</label>
        <input type="text" name="role_id" maxlength="30"/><br />
        <label >Введите пароль:</label>
        <input type="password" name="createPassword" maxlength="30"/><br />
        <!--<label >Введите пароль:</label>-->
        <!--<input type="password" name="createPassword1"  maxlength="30"/><br />-->
        <input type="submit" name="create" value="Create" />                
    </form>
</div>
