<?php
/**
 * @var Model_User $user
 */
$allUser = $view->getParam('allUser');
$count= count($allUser);
?>
<a href="#" id="showFilterForm">Фильтры</a>
<a href="/admin/createUser" id="createUser">Создать нового юзера</a>
<div id="divFilterForm" class="hide">
    <form name="filterForm" id="filterForm" method="POST" autocomplete="off">
        <label for='email_cb'>Email:</label>
        <input type="checkbox" id='email_cb' name="email_cb" maxlength="20" value=""/>
        <label for='first_name_cb'>First Name:</label>
        <input type="checkbox" id='first_name_cb' name="first_name_cb" maxlength="30" value=""/>
        <label for='last_name_cb'>Last Name:</label>
        <input type="checkbox" id='last_name_cb' name="last_name_cb" maxlength="30" value=""/>
        <label for='year_cb'>Year:</label>
        <input type="checkbox" id='year_cb' name="year_cb" maxlength="30" value=""/>
        <label for='skills_cb'>Skills:</label>
        <input type="checkbox" id='skills_cb' name="skills_cb" maxlength="30" value="1"/>
        <label for='role_id'>Role:</label>
        <input type="checkbox" id='role_id' name="role_id" maxlength="30" value="1"/>
        <input type="submit" name="selectFilter" id='selectFilter' value="Enter" />  
    </form>
</div>
<?php if($allUser) : ?>
<table border="2px" id = 'tableUsers'>
    <th>Id</th>    
    <th>Fist Name</th>    
    <th>Last Name</th> 
    <th>Skills</th>
    <th>Year</th>
    <th>Email</th>
    <th>Role id</th>
    <?php for($i = 0;$i<$count; $i++) : ?>
    <tr>
        <td><?php echo $allUser[$i]->id; ?></td>
        <td class='first_name'><?php echo $allUser[$i]->first_name; ?></td>
        <td class='last_name'><?php echo $allUser[$i]->last_name; ?></td>
        <td class='skills'><?php echo $allUser[$i]->skills; ?></td>
        <td class='year'><?php echo $allUser[$i]->year; ?></td>
        <td class='email'><?php echo $allUser[$i]->email; ?></td>
        <td class='role_id'><?php echo $allUser[$i]->role_id; ?></td>
        <td><a href="/user/profile/id/<?php echo $allUser[$i]->id; ?>">Редактировать</a></td>
        <td><a href="#" class="delete" data-user_id="<?php echo $allUser[$i]->id; ?>">Удалить</a></td>
    </tr>
    <?php endfor;?>
</table>
<?php  elseif($view->getParam('error')) : ?>
    <div class="error"><?php echo $view->getParam('error')?></div>
<?php endif; ?>